# Generated by Django 4.2.1 on 2023-05-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account', models.CharField(max_length=255, null=True)),
                ('merchant_order_id', models.IntegerField()),
                ('order_time', models.DateTimeField()),
                ('payment_id', models.IntegerField()),
                ('payment_time', models.DateTimeField(null=True)),
                ('price', models.FloatField()),
                ('stamp', models.CharField(max_length=255)),
                ('to_account', models.CharField(max_length=255)),
            ],
        ),
    ]
