# Generated by Django 4.2.1 on 2023-05-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_account_balance_alter_order_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='from_account',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_account',
            field=models.IntegerField(),
        ),
    ]
