# Generated by Django 4.2.1 on 2023-05-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_order_id_remove_refundorder_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refundorder',
            old_name='order_time',
            new_name='refund_time',
        ),
        migrations.RemoveField(
            model_name='refundorder',
            name='payment_time',
        ),
    ]
